name: Send c files to the fuzzer web service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Send request to API
        run: |
          cd CIScript
          go build -o send.out send.go 
          chmod +x send.out
          chmod +x ./runTest.sh
          ./runTest.sh $API_URL
